[general]
import = [
   "~/.config/alacritty/simple-dark.tolm"
]

[[keyboard.bindings]]
chars = "\f"
key = "L"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "U"
mode = "~Alt"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "D"
mode = "~Alt"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001BF"
key = "J"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BB"
key = "H"
mods = "Alt"

[cursor]
style = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 9

[font.bold]
family = "jetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "jetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "jetBrainsMono Nerd Font"
style = "Semibold"

[font.offset]
x = 1
y = 1

[scrolling]
history = 100000

[window]
dynamic_padding = false
opacity = 0.8
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 1
y = 1

[colors.primary]
background = "#000000"
foreground = "#ffffff"

[colors.normal]
black   = "#212121"
red     = "#f09198"
green   = "#e5e4e2"
yellow  = "#ffcb6b"
blue    = "#82aaff"
magenta = "#c792ea"
cyan    = "#89ddff"
white   = "#eeffff"

[colors.bright]
black   = "#4a4a4a"
red     = "#f07178"
green   = "#c3e88d"
yellow  = "#ffcb6b"
blue    = "#82aaff"
magenta = "#c792ea"
cyan    = "#89ddff"
white   = "#ffffff"
