#!/bin/sh

# TWO MONITORS
#xrandr --output DP-2 --primary --mode 1920x1080 --rotate normal --rate 165.00\
#  --output HDMI-0 --mode 1366x768 --rotate right --left-of DP-2
#bspc monitor DP-2 -d 1 2 3 5
#bspc monitor HDMI-0 -d 6 7 8 9 10

# ONE MONITOR
xrandr --output DP-2 --primary --mode 1920x1080 --rotate normal --rate 165.00
bspc monitor DP-2 -d 1 2 3 4 5 6 7 8 9 10

pgrep -x sxhkd > /dev/null || sxhkd &

${HOME}/.fehbg
${HOME}/.config/polybar/launch.sh
xsetroot -cursor_name left_ptr &
wmname LG3D
picom &


gap=10
PANEL_HEIGHT=24
bspc config window_gap 5;
bspc config bottom_padding $gap
bspc config left_padding $gap
bspc config right_padding $gap
# bspc config bottom_padding $(($PANEL_HEIGHT+gap))
bspc config top_padding $(($PANEL_HEIGHT+gap))
bspc config border_width         1
bspc config gapless_monocle      false
bspc config focus_follows_pointer false
bspc config auto_alternate true
bspc config auto_cancel true

bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true



# bspc config focused_border_color "#bb9af7"
bspc config normal_border_color "#222222"
bspc config focused_border_color "#44475a"
bspc config active_border_color "#ff79c6"
#bspc config presel_feedback_color "#6272a4"

bspc config normal_frame_opacity 0.0


bspc config split_ratio          0.50
