#! /bin/sh

${HOME}/.fehbg
${HOME}/.config/polybar/launch.sh

pgrep -x sxhkd > /dev/null || sxhkd &



picom &

xsetroot -cursor_name left_ptr &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10
gap=5
PANEL_HEIGHT=24
bspc config window_gap 5;
bspc config bottom_padding $gap
bspc config left_padding $gap
bspc config right_padding $gap
# bspc config bottom_padding $(($PANEL_HEIGHT+gap))
bspc config top_padding $(($PANEL_HEIGHT+gap))
bspc config border_width         1
bspc config gapless_monocle      false
bspc config focus_follows_pointer false
bspc config auto_alternate true
bspc config auto_cancel true


# bspc config focused_border_color "#bb9af7"
bspc config normal_border_color "#222222"
bspc config focused_border_color "#44475R"
bspc config active_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"

bspc config normal_frame_opacity 0.0

xsetroot -cursor_name left_ptr &

bspc config split_ratio          0.50
