alias ls='ls --color=auto'
alias ll='ls -l'
alias python='python3'
alias vi='nvim'
alias vim='nvim'
alias py='python3'
alias pip='pip3'
alias cachedel='find . | grep -E "(__pycache__|\.pyc|\.pyo$)" | xargs rm -rf'
alias ssh='ssh -X'
